### ISSUE TITLE
Architectural approach for getting Resources to Gardien

### ISSUE THREAD

**Issue by banzay** [rpelyush/gdraft#40]

**Comment by banzay** [comment]
I don't like the idea of having to pass resource from some higher-standing plug into Gardien.
What do you think about this approach, @rpelyush?  It's similar to Pundit's, but more verbose.
```
  /* inside controller */

  plug Gardien, policy: Rumbl.PostPolicy

  def index(conn) do

    // check authorization only by user
    Gardien.authorize(conn, fn ->
      posts =  Repo.all(Rumbl.Post);

      // filter resources or authorize single resource
      Gardien.authorize(conn, posts, fn(allowed_posts) ->
        render conn, "index.html", posts: allowed_posts
      end)
    end)
  end
```


```
  /* inside policy */

  def index(user) do
    user.role == "admin"
  end

  def index(user, posts) do
    Enum.filter(posts, fn(post) -> post.name == "foo" end)
  end
```

**Comment by rpelyush** [comment]
Do you mean to use this approach only for :index action (showing only records available to user) or for others too?

> I don't like the idea of having to pass resource from some higher-standing plug into Gardien.

regarding index action authorization(resolve)?

BTW, could you please clean up your example, I don't understand it :)

**Comment by rpelyush** [comment]
In case of other actions, do you mean something like this:

```elixir
def update(conn, %{"id" => id, "idea" => idea_params}) do
    idea = conn.assigns.idea
    changeset = Idea.changeset(idea, idea_params)

    Gardien.authorize(conn, idea, IdeaPolicy, fn(conn) ->
      # on authorization success handler
      case Repo.update(changeset) do
        {:ok, idea} ->
          conn
          |> put_flash(:info, "Idea updated successfully.")
          |> redirect(to: idea_path(conn, :show, idea))
        {:error, changeset} ->
          render(conn, "edit.html", idea: idea, changeset: changeset)
      end
    end, fn(conn) ->
      # on authorization failure handler
    end)
  end
```

**Comment by rpelyush** [comment]
```elixir
Gardien.authorize(conn, posts, fn(allowed_posts) ->
    render conn, "index.html", posts: allowed_posts
end)
```
What's the point in filtering posts, if you can load post available to user from db?

**Comment by banzay** [comment]
It's rather bad example. There could be DB query instead of "allowed_posts"
as a policy return value.

2016-05-03 16:33 GMT+03:00 Roman Peliushkevych <notifications@github.com>:

> Gardien.authorize(conn, posts, fn(allowed_posts) ->
>     render conn, "index.html", posts: allowed_postsend)
>
> What's the point in filtering posts, if you can load post available to
> user from db?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rpelyush/gardien/issues/40#issuecomment-216528730>
>



-- 
Слава Вареникам!

**Comment by banzay** [comment]
Bigger example.
I like letting user return anything from policy handler (Query, Array or Bool). Pundit's `Scope` seems to me unnecessary abstraction.

Basically if policy returns not nil/false - we consider user Authorized and execute success callback with return value.

P.S. Passing `conn` each time can be avoided by using `metaprogramming on the fly` :) - 
https://erlangcentral.org/wiki/index.php?title=String_Eval


```
 /* inside web.ex/def controller */
  alias Gardien.authorize, as: authorize

  /* inside controller */
  plug Gardien, Rumbl.PostPolicy

  def index(conn) do
      // authorize returns query if success
      authorize(conn, fn(allowed_posts_query) ->
        posts = MyRepo.all(allowed_posts_query)
        render conn, "index.html", posts: allowed_posts
      end)
  end

  def show(conn, %{"id" => id}) do
      // authorize doesn't need resource
      authorize(conn, fn() ->
        post = Repo.get(Rumbl.Post, id)
        render conn, "show.html", post: post
      end)
  end

  def delete(conn, %{"id" => id}) do
      // authorize needs resource
      post = Repo.get(Rumbl.Post, id)
      authorize(conn, post, fn() ->
        conn
          |> redirect(to: some_path)
      end)
  end
```

```
  /* inside policy */

  def index(user) do
    from p in Rumbl.Post, select: p, where p.user_id == user.id
  end

  def show(user) do
    user.role == "admin"
  end

  def delete(user, post) do
    post.user_id == user.id
  end
```

**Comment by rpelyush** [comment]
> P.S. Passing conn each time maybe can be avoided by using metaprogramming on the fly

What exactly do you mean?

**Comment by banzay** [comment]
lookup of 'conn' strings in bound variables

2016-05-05 9:26 GMT+03:00 Roman Peliushkevych <notifications@github.com>:

> P.S. Passing conn each time maybe can be avoided by using metaprogramming
> on the fly
>
> What exactly do you mean?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rpelyush/gardien/issues/40#issuecomment-217084338>
>



-- 
Слава Вареникам!

**Comment by rpelyush** [comment]
> I like letting user return anything from policy handler (Query, Array or Bool)

Handler can accept anything, but in case of index action
```elixir
authorize(conn, fn(allowed_posts_query) ->
        posts = MyRepo.all(allowed_posts_query)
        render conn, "index.html", posts: allowed_posts
      end)
```
you'r not only authorizing but return list of records or query. Consider view helpers. Whats the point for building query if everything you want is your policy function to return true or false in order to show/hide piece of html.
```elixir
<%- if authorize(post, :index) do %>
```
There will be cases when you want to verify separately whether user has access to action and what user can view. That's why, something like scope, is a good abstraction, because it deals with resolving available data.

**Comment by rpelyush** [comment]
As to metaprogramming, how exactly you want to use it? Do you want to mutate ```conn``` (implicitly for developer)?
